/**
 * Generates prisma/supabase_schema.sql (full DDL + RLS) and prisma/supabase_seed.sql (demo data)
 * from the Prisma schema and src/seed/data.ts. Timestamps in the seed are relative to now().
 *   npm run gen:sql
 */
import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import bcrypt from 'bcryptjs';
import { buildSeedData } from '../src/seed/data';

const root = path.resolve(__dirname, '..');
const TABLES = ['User', 'Policy', 'Claim', 'Document', 'ClaimEvent', 'Query', 'Settlement', 'ActivityLog', 'Notification'];

function schemaSql() {
  const ddl = execSync('npx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script', { cwd: root, stdio: ['ignore', 'pipe', 'ignore'] }).toString();
  const rls = TABLES.map((t) => `ALTER TABLE "${t}" ENABLE ROW LEVEL SECURITY;`).join('\n');
  return `-- Claim Saathi: full schema for Supabase Postgres (generated from prisma/schema.prisma by npm run gen:sql)
-- Prisma default naming: tables and enums use the model names.
${ddl.replace('-- CreateSchema\nCREATE SCHEMA IF NOT EXISTS "public";', '').trim()}

-- Row Level Security: ON for every table with NO public policies.
-- The API connects with the database role / service key, so the anon & authenticated keys cannot read anything.
${rls}
`;
}

const q = (v: unknown): string => {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
  if (typeof v === 'boolean') return v ? 'true' : 'false';
  if (v instanceof Date) return `'${v.toISOString().replace('T', ' ').replace('Z', '')}'`;
  if (typeof v === 'object') return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};
const ago = (sec: number) => `((now() AT TIME ZONE 'utc') - interval '${Math.round(sec)} seconds')`;
type Row = Record<string, string>;
const insert = (table: string, rows: Row[]) => {
  if (!rows.length) return '';
  const cols = Object.keys(rows[0]);
  return `INSERT INTO "${table}" (${cols.map((c) => `"${c}"`).join(', ')}) VALUES\n${rows.map((r) => `  (${cols.map((c) => r[c]).join(', ')})`).join(',\n')};\n`;
};

async function seedSql() {
  const d = await buildSeedData();
  const hash = bcrypt.hashSync('demo123', 10);
  const parts: string[] = [
    '-- Claim Saathi demo data (generated by npm run gen:sql). Re-runnable: wipes all rows first.',
    '-- Logins (password demo123): customer@claimsaathi.demo, ops@claimsaathi.demo, admin@claimsaathi.demo',
    'BEGIN;',
    `TRUNCATE ${['Notification', 'ActivityLog', 'Settlement', 'Query', 'ClaimEvent', 'Document', 'Claim', 'Policy', 'User'].map((t) => `"${t}"`).join(', ')} CASCADE;`,
  ];
  parts.push(insert('User', d.users.map((u) => ({ id: q(u.id), name: q(u.name), email: q(u.email), phone: q(u.phone), passwordHash: q(hash), role: `${q(u.role)}::"UserRole"`, city: q(u.city), createdAt: ago(u.ago), updatedAt: ago(u.ago) }))));
  parts.push(insert('Policy', d.policies.map((p) => ({
    id: q(p.id), userId: q(p.userId), insurer: q(p.extraction.insurer), planName: q(p.extraction.planName), policyNumber: q(p.policyNumber), sumInsured: q(p.extraction.sumInsured), roomRentLimit: q(p.extraction.roomRentLimit), icuLimit: q(p.extraction.icuLimit),
    coPayPercent: q(p.extraction.coPayPercent), startDate: q(p.startDate), endDate: q(p.endDate), waitingPeriods: q(p.extraction.waitingPeriods), subLimits: q(p.extraction.subLimits), exclusions: q(p.extraction.exclusions), networkHospitals: q(p.extraction.networkHospitals),
    summary: q(p.extraction.summaryEnglish), summaryHindi: q(p.extraction.summaryHindi), fileUrl: q(p.fileUrl), rawText: q(p.rawText), createdAt: ago(p.ago), updatedAt: ago(p.ago),
  }))));
  parts.push(insert('Claim', d.claims.map((c) => ({
    id: q(c.id), claimNumber: q(c.claimNumber), userId: q(c.userId), policyId: q(c.policyId), patientName: q(c.patientName), hospital: q(c.hospital), hospitalCity: q(c.hospitalCity), isNetworkHospital: 'true', reason: q(c.reason), treatment: q(c.treatment),
    claimType: `${q(c.claimType)}::"ClaimType"`, admissionType: `${q(c.admissionType)}::"AdmissionType"`, isAccident: q(c.isAccident), admissionDate: q(c.admissionDate), dischargeDate: q(c.dischargeDate), roomType: q(c.roomType), roomRentPerDay: q(c.roomRentPerDay), days: q(c.days),
    estimatedAmount: q(c.estimatedAmount), billAmount: q(c.billAmount), billItems: q(c.billItems), status: `${q(c.status)}::"ClaimStatus"`, aiSummary: q(c.aiSummary), aiSuggestion: q(c.aiSuggestion), aiConfidence: q(c.aiConfidence), riskLevel: q(c.riskLevel), riskFlags: q(c.riskFlags),
    reminderCount: q(c.reminderCount), isDemo: q(true), lastActivityAt: ago(c.lastActivityAgo), createdAt: ago(c.ago), updatedAt: ago(c.lastActivityAgo),
  }))));
  parts.push(insert('Document', d.documents.map((x) => ({
    id: q(x.id), claimId: q(x.claimId), type: `${q(x.type)}::"DocumentType"`, fileName: q(x.fileName), fileUrl: q(x.fileUrl), mimeType: q(x.mimeType), size: q(x.size), status: `${q(x.status)}::"DocumentStatus"`, confidence: q(x.confidence),
    validationResult: q(x.validation), extractedData: q(x.validation.extracted), reviewedBy: 'NULL', reviewNote: 'NULL', createdAt: ago(x.ago), updatedAt: ago(x.ago),
  }))));
  parts.push(insert('ClaimEvent', d.events.map((e) => ({ id: q(e.id), claimId: q(e.claimId), status: `${q(e.status)}::"ClaimStatus"`, title: q(e.title), description: q(e.description), actor: `${q(e.actor)}::"ActorType"`, createdAt: ago(e.ago) }))));
  parts.push(insert('Query', d.queries.map((x) => ({
    id: q(x.id), claimId: q(x.claimId), message: q(x.message), requestedDocType: x.requestedDocType ? `${q(x.requestedDocType)}::"DocumentType"` : 'NULL', response: q(x.response), status: `${q(x.status)}::"QueryStatus"`, createdBy: `${q(x.createdBy)}::"ActorType"`,
    respondedAt: x.respondedAgo != null ? ago(x.respondedAgo) : 'NULL', closedAt: x.closedAgo != null ? ago(x.closedAgo) : 'NULL', createdAt: ago(x.ago), updatedAt: ago(Math.min(x.ago, x.closedAgo ?? x.ago, x.respondedAgo ?? x.ago)),
  }))));
  parts.push(insert('Settlement', d.settlements.map((s) => ({
    id: q(s.id), claimId: q(s.claimId), billAmount: q(s.result.billAmount), deductions: q(s.result.deductions), coPayAmount: q(s.result.coPayAmount), approvedAmount: q(s.result.approvedAmount), explanation: q(s.result.explanation), status: `${q(s.status)}::"SettlementStatus"`,
    utr: q(s.utr), paidAt: s.paidAgo != null ? ago(s.paidAgo) : 'NULL', createdAt: ago(s.ago), updatedAt: ago(s.paidAgo ?? s.ago),
  }))));
  parts.push(insert('ActivityLog', d.logs.map((l) => ({ id: q(l.id), claimId: q(l.claimId), actor: `${q(l.actor)}::"ActorType"`, actorName: q(l.actorName), action: q(l.action), reason: q(l.reason), confidence: q(l.confidence), meta: 'NULL', createdAt: ago(l.ago) }))));
  parts.push(insert('Notification', d.notifications.map((n) => ({ id: q(n.id), userId: q(n.userId), claimId: q(n.claimId), type: `${q(n.type)}::"NotificationType"`, title: q(n.title), body: q(n.body), read: q(n.read), createdAt: ago(n.ago) }))));
  parts.push('COMMIT;');
  return parts.join('\n');
}

(async () => {
  fs.writeFileSync(path.join(root, 'prisma', 'supabase_schema.sql'), schemaSql());
  fs.writeFileSync(path.join(root, 'prisma', 'supabase_seed.sql'), await seedSql());
  console.log('Wrote prisma/supabase_schema.sql and prisma/supabase_seed.sql');
})();
